//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.03 at 09:49:42 AM CET 
//


package bzh.terrevirtuelle.navisu.gpx;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.navisu.gpx.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Gpx_QNAME = new QName("http://www.topografix.com/GPX/1/1", "gpx");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.navisu.gpx.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Gpx }
     * 
     */
    public Gpx createGpxType() {
        return new Gpx();
    }

    /**
     * Create an instance of {@link Wpt }
     * 
     */
    public Wpt createWptType() {
        return new Wpt();
    }

    /**
     * Create an instance of {@link Bounds }
     * 
     */
    public Bounds createBoundsType() {
        return new Bounds();
    }

    /**
     * Create an instance of {@link Copyright }
     * 
     */
    public Copyright createCopyrightType() {
        return new Copyright();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLinkType() {
        return new Link();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadataType() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link Extensions }
     * 
     */
    public Extensions createExtensionsType() {
        return new Extensions();
    }

    /**
     * Create an instance of {@link Rte }
     * 
     */
    public Rte createRteType() {
        return new Rte();
    }

    /**
     * Create an instance of {@link Email }
     * 
     */
    public Email createEmailType() {
        return new Email();
    }

    /**
     * Create an instance of {@link Ptseg }
     * 
     */
    public Ptseg createPtsegType() {
        return new Ptseg();
    }

    /**
     * Create an instance of {@link Pt }
     * 
     */
    public Pt createPtType() {
        return new Pt();
    }

    /**
     * Create an instance of {@link Trkseg }
     * 
     */
    public Trkseg createTrksegType() {
        return new Trkseg();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPersonType() {
        return new Person();
    }

    /**
     * Create an instance of {@link Trk }
     * 
     */
    public Trk createTrkType() {
        return new Trk();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Gpx }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.topografix.com/GPX/1/1", name = "gpx")
    public JAXBElement<Gpx> createGpx(Gpx value) {
        return new JAXBElement<Gpx>(_Gpx_QNAME, Gpx.class, null, value);
    }

}
