/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bzh.terrevirtuelle.navisu.domain.country;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author serge
 * @date Jan 9, 2017
 */
public class CountryCode {

    public static final Map<String, String> CODE = Collections.unmodifiableMap(new HashMap<String, String>() {
        {
            put("AlandIslands", "AX");
            put("Albania", "AL");
            put("Algeria", "DZ");
            put("AmericanSamoa", "AS");
            put("Andorra", "AD");
            put("Angola", "AO");
            put("Anguilla", "AI");
            put("Antarctica", "AQ");
            put("AntiguaandBarbuda", "AG");
            put("Argentina", "AR");
            put("Armenia", "AM");
            put("Aruba", "AW");
            put("Australia", "AU");
            put("Austria", "AT");
            put("Azerbaijan", "AZ");
            put("Bahamas", "BS");
            put("Bahrain", "BH");
            put("Bangladesh", "BD");
            put("Barbados", "BB");
            put("Belarus", "BY");
            put("Belgium", "BE");
            put("Belize", "BZ");
            put("Benin", "BJ");
            put("Bermuda", "BM");
            put("Bhutan", "BT");
            put("Bolivia", "BO");
            put("BosniaandHerzegovina", "BA");
            put("Botswana", "BW");
            put("BouvetIsland", "BV");
            put("Brazil", "BR");
            put("BritishVirginIslands", "VG");
            put("BritishIndianOceanTerritory", "IO");
            put("BruneiDarussalam", "BN");
            put("Bulgaria", "BG");
            put("BurkinaFaso", "BF");
            put("Burundi", "BI");
            put("Cambodia", "KH");
            put("Cameroon", "CM");
            put("Canada", "CA");
            put("CapeVerde", "CV");
            put("CaymanIslands", "KY");
            put("CentralAfricanRepublic", "CF");
            put("Chad", "TD");
            put("Chile", "CL");
            put("China", "CN");
            put("HongKong", "HK");
            put("Macao", "MO");
            put("ChristmasIsland", "CX");
            put("Cocos(Keeling)Islands", "CC");
            put("Colombia", "CO");
            put("Comoros", "KM");
            put("Congo(Brazzaville)", "CG");
            put("Congo DemocraticRepublicofthe", "CD");
            put("CookIslands", "CK");
            put("CostaRica", "CR");
            put("Côted'Ivoire", "CI");
            put("Croatia", "HR");
            put("Cuba", "CU");
            put("Cyprus", "CY");
            put("CzechRepublic", "CZ");
            put("Denmark", "DK");
            put("Djibouti", "DJ");
            put("Dominica", "DM");
            put("DominicanRepublic", "DO");
            put("Ecuador", "EC");
            put("Egypt", "EG");
            put("ElSalvador", "SV");
            put("EquatorialGuinea", "GQ");
            put("Eritrea", "ER");
            put("Estonia", "EE");
            put("Ethiopia", "ET");
            put("FalklandIslands", "FK");
            put("FaroeIslands", "FO");
            put("Fiji", "FJ");
            put("Finland", "FI");
            put("France", "FR");
            put("FrenchGuiana", "GF");
            put("FrenchPolynesia", "PF");
            put("FrenchSouthernTerritories", "TF");
            put("Gabon", "GA");
            put("Gambia", "GM");
            put("Georgia", "GE");
            put("Germany", "DE");
            put("Ghana", "GH");
            put("Gibraltar", "GI");
            put("Greece", "GR");
            put("Greenland", "GL");
            put("Grenada", "GD");
            put("Guadeloupe", "GP");
            put("Guam", "GU");
            put("Guatemala", "GT");
            put("Guernsey", "GG");
            put("Guinea", "GN");
            put("Guinea-Bissau", "GW");
            put("Guyana", "GY");
            put("Haiti", "HT");
            put("HeardIslandandMcdonaldIslands", "HM");
            put("HolySee(VaticanCityState)", "VA");
            put("Honduras", "HN");
            put("Hungary", "HU");
            put("Iceland", "IS");
            put("India", "IN");
            put("Indonesia", "ID");
            put("Iran IslamicRepublicof", "IR");
            put("Iraq", "IQ");
            put("Ireland", "IE");
            put("IsleofMan", "IM");
            put("Israel", "IL");
            put("Italy", "IT");
            put("Jamaica", "JM");
            put("Japan", "JP");
            put("Jersey", "JE");
            put("Jordan", "JO");
            put("Kazakhstan", "KZ");
            put("Kenya", "KE");
            put("Kiribati", "KI");
            put("Korea DemocraticPeople'sRepublicof", "KP");
            put("Korea Republicof", "KR");
            put("Kuwait", "KW");
            put("Kyrgyzstan", "KG");
            put("LaoPDR", "LA");
            put("Latvia", "LV");
            put("Lebanon", "LB");
            put("Lesotho", "LS");
            put("Liberia", "LR");
            put("Libya", "LY");
            put("Liechtenstein", "LI");
            put("Lithuania", "LT");
            put("Luxembourg", "LU");
            put("Macedonia Republicof", "MK");
            put("Madagascar", "MG");
            put("Malawi", "MW");
            put("Malaysia", "MY");
            put("Maldives", "MV");
            put("Mali", "ML");
            put("Malta", "MT");
            put("MarshallIslands", "MH");
            put("Martinique", "MQ");
            put("Mauritania", "MR");
            put("Mauritius", "MU");
            put("Mayotte", "YT");
            put("Mexico", "MX");
            put("Micronesia FederatedStatesof", "FM");
            put("Moldova", "MD");
            put("Monaco", "MC");
            put("Mongolia", "MN");
            put("Montenegro", "ME");
            put("Montserrat", "MS");
            put("Morocco", "MA");
            put("Mozambique", "MZ");
            put("Myanmar", "MM");
            put("Namibia", "NA");
            put("Nauru", "NR");
            put("Nepal", "NP");
            put("Netherlands", "NL");
            put("NetherlandsAntilles", "AN");
            put("NewCaledonia", "NC");
            put("NewZealand", "NZ");
            put("Nicaragua", "NI");
            put("Niger", "NE");
            put("Nigeria", "NG");
            put("Niue", "NU");
            put("NorfolkIsland", "NF");
            put("NorthernMarianaIslands", "MP");
            put("Norway", "NO");
            put("Oman", "OM");
            put("Pakistan", "PK");
            put("Palau", "PW");
            put("PalestinianTerritory Occupied", "PS");
            put("Panama", "PA");
            put("PapuaNewGuinea", "PG");
            put("Paraguay", "PY");
            put("Peru", "PE");
            put("Philippines", "PH");
            put("Pitcairn", "PN");
            put("Poland", "PL");
            put("Portugal", "PT");
            put("PuertoRico", "PR");
            put("Qatar", "QA");
            put("Réunion", "RE");
            put("Romania", "RO");
            put("RussianFederation", "RU");
            put("Rwanda", "RW");
            put("Saint-Barthélemy", "BL");
            put("SaintHelena", "SH");
            put("SaintKittsandNevis", "KN");
            put("SaintLucia", "LC");
            put("Saint-Martin(Frenchpart)", "MF");
            put("SaintPierreandMiquelon", "PM");
            put("SaintVincentandGrenadines", "VC");
            put("Samoa", "WS");
            put("SanMarino", "SM");
            put("SaoTomeandPrincipe", "ST");
            put("SaudiArabia", "SA");
            put("Senegal", "SN");
            put("Serbia", "RS");
            put("Seychelles", "SC");
            put("SierraLeone", "SL");
            put("Singapore", "SG");
            put("Slovakia", "SK");
            put("Slovenia", "SI");
            put("SolomonIslands", "SB");
            put("Somalia", "SO");
            put("SouthAfrica", "ZA");
            put("SouthGeorgiaandtheSouthSandwichIslands", "GS");
            put("SouthSudan", "SS");
            put("Spain", "ES");
            put("SriLanka", "LK");
            put("Sudan", "SD");
            put("Suriname*", "SR");
            put("SvalbardandJanMayenIslands", "SJ");
            put("Swaziland", "SZ");
            put("Sweden", "SE");
            put("Switzerland", "CH");
            put("SyrianArabRepublic(Syria)", "SY");
            put("Taiwan RepublicofChina", "TW");
            put("Tajikistan", "TJ");
            put("Tanzania UnitedRepublicof", "TZ");
            put("Thailand", "TH");
            put("Timor-Leste", "TL");
            put("Togo", "TG");
            put("Tokelau", "TK");
            put("Tonga", "TO");
            put("TrinidadandTobago", "TT");
            put("Tunisia", "TN");
            put("Turkey", "TR");
            put("Turkmenistan", "TM");
            put("TurksandCaicosIslands", "TC");
            put("Tuvalu", "TV");
            put("Uganda", "UG");
            put("Ukraine", "UA");
            put("UnitedArabEmirates", "AE");
            put("UnitedKingdom", "GB");
            put("UnitedStatesofAmerica", "US");
            put("UnitedStatesMinorOutlyingIslands", "UM");
            put("Uruguay", "UY");
            put("Uzbekistan", "UZ");
            put("Vanuatu", "VU");
            put("Venezuela(BolivarianRepublicof)", "VE");
            put("VietNam", "VN");
            put("VirginIslands US", "VI");
            put("WallisandFutunaIslands", "WF");
            put("WesternSahara", "EH");
            put("Yemen", "YE");
            put("Zambia", "ZM");
            put("Zimbabwe", "ZW");
        }
    });
}
