//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.03 at 04:05:58 PM CET 
//


package bzh.terrevirtuelle.navisu.domain.rtz;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Leg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Leg">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="starboardXTD" type="{http://www.cirm.org/RTZ/1/0}XtdType" />
 *       &lt;attribute name="portsideXTD" type="{http://www.cirm.org/RTZ/1/0}XtdType" />
 *       &lt;attribute name="safetyContour" type="{http://www.cirm.org/RTZ/1/0}LengthType" />
 *       &lt;attribute name="safetyDepth" type="{http://www.cirm.org/RTZ/1/0}LengthType" />
 *       &lt;attribute name="geometryType" type="{http://www.cirm.org/RTZ/1/0}GeometryType" />
 *       &lt;attribute name="speedMin" type="{http://www.cirm.org/RTZ/1/0}SpeedType" />
 *       &lt;attribute name="speedMax" type="{http://www.cirm.org/RTZ/1/0}SpeedType" />
 *       &lt;attribute name="draughtForward" type="{http://www.cirm.org/RTZ/1/0}LengthType" />
 *       &lt;attribute name="draughtAft" type="{http://www.cirm.org/RTZ/1/0}LengthType" />
 *       &lt;attribute name="staticUKC" type="{http://www.cirm.org/RTZ/1/0}LengthType" />
 *       &lt;attribute name="dynamicUKC" type="{http://www.cirm.org/RTZ/1/0}LengthType" />
 *       &lt;attribute name="masthead" type="{http://www.cirm.org/RTZ/1/0}LengthType" />
 *       &lt;attribute name="legReport" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="legInfo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="legNote1" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="legNote2" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Leg")
public class Leg {

    @XmlAttribute(name = "starboardXTD")
    protected BigDecimal starboardXTD;
    @XmlAttribute(name = "portsideXTD")
    protected BigDecimal portsideXTD;
    @XmlAttribute(name = "safetyContour")
    protected BigDecimal safetyContour;
    @XmlAttribute(name = "safetyDepth")
    protected BigDecimal safetyDepth;
    @XmlAttribute(name = "geometryType")
    protected GeometryType geometryType;
    @XmlAttribute(name = "speedMin")
    protected BigDecimal speedMin;
    @XmlAttribute(name = "speedMax")
    protected BigDecimal speedMax;
    @XmlAttribute(name = "draughtForward")
    protected BigDecimal draughtForward;
    @XmlAttribute(name = "draughtAft")
    protected BigDecimal draughtAft;
    @XmlAttribute(name = "staticUKC")
    protected BigDecimal staticUKC;
    @XmlAttribute(name = "dynamicUKC")
    protected BigDecimal dynamicUKC;
    @XmlAttribute(name = "masthead")
    protected BigDecimal masthead;
    @XmlAttribute(name = "legReport")
    protected String legReport;
    @XmlAttribute(name = "legInfo")
    protected String legInfo;
    @XmlAttribute(name = "legNote1")
    protected String legNote1;
    @XmlAttribute(name = "legNote2")
    protected String legNote2;

    /**
     * Gets the value of the starboardXTD property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStarboardXTD() {
        return starboardXTD;
    }

    /**
     * Sets the value of the starboardXTD property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStarboardXTD(BigDecimal value) {
        this.starboardXTD = value;
    }

    /**
     * Gets the value of the portsideXTD property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPortsideXTD() {
        return portsideXTD;
    }

    /**
     * Sets the value of the portsideXTD property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPortsideXTD(BigDecimal value) {
        this.portsideXTD = value;
    }

    /**
     * Gets the value of the safetyContour property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSafetyContour() {
        return safetyContour;
    }

    /**
     * Sets the value of the safetyContour property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSafetyContour(BigDecimal value) {
        this.safetyContour = value;
    }

    /**
     * Gets the value of the safetyDepth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSafetyDepth() {
        return safetyDepth;
    }

    /**
     * Sets the value of the safetyDepth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSafetyDepth(BigDecimal value) {
        this.safetyDepth = value;
    }

    /**
     * Gets the value of the geometryType property.
     * 
     * @return
     *     possible object is
     *     {@link GeometryType }
     *     
     */
    public GeometryType getGeometryType() {
        return geometryType;
    }

    /**
     * Sets the value of the geometryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeometryType }
     *     
     */
    public void setGeometryType(GeometryType value) {
        this.geometryType = value;
    }

    /**
     * Gets the value of the speedMin property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSpeedMin() {
        return speedMin;
    }

    /**
     * Sets the value of the speedMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSpeedMin(BigDecimal value) {
        this.speedMin = value;
    }

    /**
     * Gets the value of the speedMax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSpeedMax() {
        return speedMax;
    }

    /**
     * Sets the value of the speedMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSpeedMax(BigDecimal value) {
        this.speedMax = value;
    }

    /**
     * Gets the value of the draughtForward property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDraughtForward() {
        return draughtForward;
    }

    /**
     * Sets the value of the draughtForward property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDraughtForward(BigDecimal value) {
        this.draughtForward = value;
    }

    /**
     * Gets the value of the draughtAft property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDraughtAft() {
        return draughtAft;
    }

    /**
     * Sets the value of the draughtAft property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDraughtAft(BigDecimal value) {
        this.draughtAft = value;
    }

    /**
     * Gets the value of the staticUKC property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStaticUKC() {
        return staticUKC;
    }

    /**
     * Sets the value of the staticUKC property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStaticUKC(BigDecimal value) {
        this.staticUKC = value;
    }

    /**
     * Gets the value of the dynamicUKC property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDynamicUKC() {
        return dynamicUKC;
    }

    /**
     * Sets the value of the dynamicUKC property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDynamicUKC(BigDecimal value) {
        this.dynamicUKC = value;
    }

    /**
     * Gets the value of the masthead property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMasthead() {
        return masthead;
    }

    /**
     * Sets the value of the masthead property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMasthead(BigDecimal value) {
        this.masthead = value;
    }

    /**
     * Gets the value of the legReport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegReport() {
        return legReport;
    }

    /**
     * Sets the value of the legReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegReport(String value) {
        this.legReport = value;
    }

    /**
     * Gets the value of the legInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegInfo() {
        return legInfo;
    }

    /**
     * Sets the value of the legInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegInfo(String value) {
        this.legInfo = value;
    }

    /**
     * Gets the value of the legNote1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegNote1() {
        return legNote1;
    }

    /**
     * Sets the value of the legNote1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegNote1(String value) {
        this.legNote1 = value;
    }

    /**
     * Gets the value of the legNote2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegNote2() {
        return legNote2;
    }

    /**
     * Sets the value of the legNote2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegNote2(String value) {
        this.legNote2 = value;
    }

    @Override
    public String toString() {
        return "Leg{" + "starboardXTD=" + starboardXTD + ", portsideXTD=" + portsideXTD + ", safetyContour=" + safetyContour + ", safetyDepth=" + safetyDepth + ", geometryType=" + geometryType + ", speedMin=" + speedMin + ", speedMax=" + speedMax + ", draughtForward=" + draughtForward + ", draughtAft=" + draughtAft + ", staticUKC=" + staticUKC + ", dynamicUKC=" + dynamicUKC + ", masthead=" + masthead + ", legReport=" + legReport + ", legInfo=" + legInfo + ", legNote1=" + legNote1 + ", legNote2=" + legNote2 + '}';
    }

}
