//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.03 at 04:05:58 PM CET 
//


package bzh.terrevirtuelle.navisu.domain.rtz;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bzh.terrevirtuelle.navisu.domain.rtz package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Route_QNAME = new QName("http://www.cirm.org/RTZ/1/0", "route");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bzh.terrevirtuelle.navisu.domain.rtz
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Route }
     * 
     */
    public Route createRoute() {
        return new Route();
    }

    /**
     * Create an instance of {@link Waypoints }
     * 
     */
    public Waypoints createWaypoints() {
        return new Waypoints();
    }

    /**
     * Create an instance of {@link Schedules }
     * 
     */
    public Schedules createSchedules() {
        return new Schedules();
    }

    /**
     * Create an instance of {@link Manual }
     * 
     */
    public Manual createManual() {
        return new Manual();
    }

    /**
     * Create an instance of {@link Calculated }
     * 
     */
    public Calculated createCalculated() {
        return new Calculated();
    }

    /**
     * Create an instance of {@link Extensions }
     * 
     */
    public Extensions createExtensions() {
        return new Extensions();
    }

    /**
     * Create an instance of {@link DefaultWaypoint }
     * 
     */
    public DefaultWaypoint createDefaultWaypoint() {
        return new DefaultWaypoint();
    }

    /**
     * Create an instance of {@link Leg }
     * 
     */
    public Leg createLeg() {
        return new Leg();
    }

    /**
     * Create an instance of {@link ScheduleElement }
     * 
     */
    public ScheduleElement createScheduleElement() {
        return new ScheduleElement();
    }

    /**
     * Create an instance of {@link Schedule }
     * 
     */
    public Schedule createSchedule() {
        return new Schedule();
    }

    /**
     * Create an instance of {@link Waypoint }
     * 
     */
    public Waypoint createWaypoint() {
        return new Waypoint();
    }

    /**
     * Create an instance of {@link RouteInfo }
     * 
     */
    public RouteInfo createRouteInfo() {
        return new RouteInfo();
    }

    /**
     * Create an instance of {@link GMPoint }
     * 
     */
    public GMPoint createGMPoint() {
        return new GMPoint();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Route }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cirm.org/RTZ/1/0", name = "route")
    public JAXBElement<Route> createRoute(Route value) {
        return new JAXBElement<Route>(_Route_QNAME, Route.class, null, value);
    }

}
