//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.03 at 04:05:58 PM CET 
//
package bzh.terrevirtuelle.navisu.domain.rtz;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 *
 * RTZ files contain a number of waypoints, followed with auxiliary schedules.
 * You can add your own elements to the extension section of the RTZ document.
 *
 *
 * <p>
 * Java class for Route complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="Route">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="routeInfo" type="{http://www.cirm.org/RTZ/1/0}RouteInfo"/>
 *         &lt;element name="waypoints" type="{http://www.cirm.org/RTZ/1/0}Waypoints"/>
 *         &lt;element name="schedules" type="{http://www.cirm.org/RTZ/1/0}Schedules" minOccurs="0"/>
 *         &lt;element name="extensions" type="{http://www.cirm.org/RTZ/1/0}Extensions" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Route", propOrder = {
    "routeInfo",
    "waypoints",
    "schedules",
    "extensions"
})
@XmlRootElement
public class Route {

    @XmlElement(required = true)
    protected RouteInfo routeInfo;
    @XmlElement(required = true)
    protected Waypoints waypoints;
    protected Schedules schedules;
    protected Extensions extensions;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    public Route() {
    }

    /**
     * Gets the value of the routeInfo property.
     *
     * @return possible object is {@link RouteInfo }
     *
     */
    public RouteInfo getRouteInfo() {
        return routeInfo;
    }

    /**
     * Sets the value of the routeInfo property.
     *
     * @param value allowed object is {@link RouteInfo }
     *
     */
    public void setRouteInfo(RouteInfo value) {
        this.routeInfo = value;
    }

    /**
     * Gets the value of the waypoints property.
     *
     * @return possible object is {@link Waypoints }
     *
     */
    public Waypoints getWaypoints() {
        return waypoints;
    }

    /**
     * Sets the value of the waypoints property.
     *
     * @param value allowed object is {@link Waypoints }
     *
     */
    public void setWaypoints(Waypoints value) {
        this.waypoints = value;
    }

    /**
     * Gets the value of the schedules property.
     *
     * @return possible object is {@link Schedules }
     *
     */
    public Schedules getSchedules() {
        return schedules;
    }

    /**
     * Sets the value of the schedules property.
     *
     * @param value allowed object is {@link Schedules }
     *
     */
    public void setSchedules(Schedules value) {
        this.schedules = value;
    }

    /**
     * Gets the value of the extensions property.
     *
     * @return possible object is {@link Extensions }
     *
     */
    public Extensions getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     *
     * @param value allowed object is {@link Extensions }
     *
     */
    public void setExtensions(Extensions value) {
        this.extensions = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setVersion(String value) {
        this.version = value;
    }

    @Override
    public String toString() {
        return "Route{"
                + routeInfo != null ? "routeInfo=" + routeInfo : ""
                        + waypoints != null ? ", waypoints=" + waypoints : ""
                                + schedules != null ? ", schedules=" + schedules : ""
                                        + extensions != null ? ", extensions=" + extensions : ""
                                                + version != null ? ", version=" + version : ""
                                                        + '}';
    }

}
