//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.03 at 04:05:58 PM CET 
//


package bzh.terrevirtuelle.navisu.domain.rtz;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for RouteInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RouteInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="extensions" type="{http://www.cirm.org/RTZ/1/0}Extensions" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="routeName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="routeAuthor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="routeStatus" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="validityPeriodStart" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="validityPeriodStop" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="vesselName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="vesselMMSI" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="vesselIMO" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="vesselVoyage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="vesselDisplacement" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="vesselCargo" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="vesselGM" type="{http://www.cirm.org/RTZ/1/0}LengthType" />
 *       &lt;attribute name="optimizationMethod" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="vesselMaxRoll" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="vesselMaxWave" type="{http://www.cirm.org/RTZ/1/0}LengthType" />
 *       &lt;attribute name="vesselMaxWind" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="vesselSpeedMax" type="{http://www.cirm.org/RTZ/1/0}SpeedType" />
 *       &lt;attribute name="vesselServiceMin" type="{http://www.cirm.org/RTZ/1/0}SpeedType" />
 *       &lt;attribute name="vesselServiceMax" type="{http://www.cirm.org/RTZ/1/0}SpeedType" />
 *       &lt;attribute name="routeChangesHistory" type="{http://www.cirm.org/RTZ/1/0}SpeedType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RouteInfo", propOrder = {
    "extensions"
})
public class RouteInfo {

    protected Extensions extensions;
    @XmlAttribute(name = "routeName", required = true)
    protected String routeName;
    @XmlAttribute(name = "routeAuthor")
    protected String routeAuthor;
    @XmlAttribute(name = "routeStatus")
    protected String routeStatus;
    @XmlAttribute(name = "validityPeriodStart")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validityPeriodStart;
    @XmlAttribute(name = "validityPeriodStop")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validityPeriodStop;
    @XmlAttribute(name = "vesselName")
    protected String vesselName;
    @XmlAttribute(name = "vesselMMSI")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger vesselMMSI;
    @XmlAttribute(name = "vesselIMO")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger vesselIMO;
    @XmlAttribute(name = "vesselVoyage")
    protected String vesselVoyage;
    @XmlAttribute(name = "vesselDisplacement")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger vesselDisplacement;
    @XmlAttribute(name = "vesselCargo")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger vesselCargo;
    @XmlAttribute(name = "vesselGM")
    protected BigDecimal vesselGM;
    @XmlAttribute(name = "optimizationMethod")
    protected String optimizationMethod;
    @XmlAttribute(name = "vesselMaxRoll")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger vesselMaxRoll;
    @XmlAttribute(name = "vesselMaxWave")
    protected BigDecimal vesselMaxWave;
    @XmlAttribute(name = "vesselMaxWind")
    protected BigDecimal vesselMaxWind;
    @XmlAttribute(name = "vesselSpeedMax")
    protected BigDecimal vesselSpeedMax;
    @XmlAttribute(name = "vesselServiceMin")
    protected BigDecimal vesselServiceMin;
    @XmlAttribute(name = "vesselServiceMax")
    protected BigDecimal vesselServiceMax;
    @XmlAttribute(name = "routeChangesHistory")
    protected BigDecimal routeChangesHistory;

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link Extensions }
     *     
     */
    public Extensions getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Extensions }
     *     
     */
    public void setExtensions(Extensions value) {
        this.extensions = value;
    }

    /**
     * Gets the value of the routeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRouteName() {
        return routeName;
    }

    /**
     * Sets the value of the routeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRouteName(String value) {
        this.routeName = value;
    }

    /**
     * Gets the value of the routeAuthor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRouteAuthor() {
        return routeAuthor;
    }

    /**
     * Sets the value of the routeAuthor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRouteAuthor(String value) {
        this.routeAuthor = value;
    }

    /**
     * Gets the value of the routeStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRouteStatus() {
        return routeStatus;
    }

    /**
     * Sets the value of the routeStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRouteStatus(String value) {
        this.routeStatus = value;
    }

    /**
     * Gets the value of the validityPeriodStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidityPeriodStart() {
        return validityPeriodStart;
    }

    /**
     * Sets the value of the validityPeriodStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidityPeriodStart(XMLGregorianCalendar value) {
        this.validityPeriodStart = value;
    }

    /**
     * Gets the value of the validityPeriodStop property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidityPeriodStop() {
        return validityPeriodStop;
    }

    /**
     * Sets the value of the validityPeriodStop property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidityPeriodStop(XMLGregorianCalendar value) {
        this.validityPeriodStop = value;
    }

    /**
     * Gets the value of the vesselName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVesselName() {
        return vesselName;
    }

    /**
     * Sets the value of the vesselName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVesselName(String value) {
        this.vesselName = value;
    }

    /**
     * Gets the value of the vesselMMSI property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVesselMMSI() {
        return vesselMMSI;
    }

    /**
     * Sets the value of the vesselMMSI property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVesselMMSI(BigInteger value) {
        this.vesselMMSI = value;
    }

    /**
     * Gets the value of the vesselIMO property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVesselIMO() {
        return vesselIMO;
    }

    /**
     * Sets the value of the vesselIMO property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVesselIMO(BigInteger value) {
        this.vesselIMO = value;
    }

    /**
     * Gets the value of the vesselVoyage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVesselVoyage() {
        return vesselVoyage;
    }

    /**
     * Sets the value of the vesselVoyage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVesselVoyage(String value) {
        this.vesselVoyage = value;
    }

    /**
     * Gets the value of the vesselDisplacement property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVesselDisplacement() {
        return vesselDisplacement;
    }

    /**
     * Sets the value of the vesselDisplacement property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVesselDisplacement(BigInteger value) {
        this.vesselDisplacement = value;
    }

    /**
     * Gets the value of the vesselCargo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVesselCargo() {
        return vesselCargo;
    }

    /**
     * Sets the value of the vesselCargo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVesselCargo(BigInteger value) {
        this.vesselCargo = value;
    }

    /**
     * Gets the value of the vesselGM property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVesselGM() {
        return vesselGM;
    }

    /**
     * Sets the value of the vesselGM property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVesselGM(BigDecimal value) {
        this.vesselGM = value;
    }

    /**
     * Gets the value of the optimizationMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptimizationMethod() {
        return optimizationMethod;
    }

    /**
     * Sets the value of the optimizationMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptimizationMethod(String value) {
        this.optimizationMethod = value;
    }

    /**
     * Gets the value of the vesselMaxRoll property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVesselMaxRoll() {
        return vesselMaxRoll;
    }

    /**
     * Sets the value of the vesselMaxRoll property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVesselMaxRoll(BigInteger value) {
        this.vesselMaxRoll = value;
    }

    /**
     * Gets the value of the vesselMaxWave property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVesselMaxWave() {
        return vesselMaxWave;
    }

    /**
     * Sets the value of the vesselMaxWave property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVesselMaxWave(BigDecimal value) {
        this.vesselMaxWave = value;
    }

    /**
     * Gets the value of the vesselMaxWind property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVesselMaxWind() {
        return vesselMaxWind;
    }

    /**
     * Sets the value of the vesselMaxWind property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVesselMaxWind(BigDecimal value) {
        this.vesselMaxWind = value;
    }

    /**
     * Gets the value of the vesselSpeedMax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVesselSpeedMax() {
        return vesselSpeedMax;
    }

    /**
     * Sets the value of the vesselSpeedMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVesselSpeedMax(BigDecimal value) {
        this.vesselSpeedMax = value;
    }

    /**
     * Gets the value of the vesselServiceMin property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVesselServiceMin() {
        return vesselServiceMin;
    }

    /**
     * Sets the value of the vesselServiceMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVesselServiceMin(BigDecimal value) {
        this.vesselServiceMin = value;
    }

    /**
     * Gets the value of the vesselServiceMax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVesselServiceMax() {
        return vesselServiceMax;
    }

    /**
     * Sets the value of the vesselServiceMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVesselServiceMax(BigDecimal value) {
        this.vesselServiceMax = value;
    }

    /**
     * Gets the value of the routeChangesHistory property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRouteChangesHistory() {
        return routeChangesHistory;
    }

    /**
     * Sets the value of the routeChangesHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRouteChangesHistory(BigDecimal value) {
        this.routeChangesHistory = value;
    }

    @Override
    public String toString() {
        return "RouteInfo{" + "extensions=" + extensions 
                + ", routeName=" + routeName 
                + ", routeAuthor=" + routeAuthor 
                + ", routeStatus=" + routeStatus 
                + ", validityPeriodStart=" + validityPeriodStart 
                + ", validityPeriodStop=" + validityPeriodStop 
                + ", vesselName=" 
                + vesselName + ", vesselMMSI=" 
                + vesselMMSI + ", vesselIMO=" 
                + vesselIMO + ", vesselVoyage=" 
                + vesselVoyage + ", vesselDisplacement=" 
                + vesselDisplacement + ", vesselCargo=" 
                + vesselCargo + ", vesselGM=" 
                + vesselGM + ", optimizationMethod=" 
                + optimizationMethod + ", vesselMaxRoll=" 
                + vesselMaxRoll + ", vesselMaxWave=" 
                + vesselMaxWave + ", vesselMaxWind=" 
                + vesselMaxWind + ", vesselSpeedMax=" 
                + vesselSpeedMax + ", vesselServiceMin=" 
                + vesselServiceMin + ", vesselServiceMax=" 
                + vesselServiceMax + ", routeChangesHistory=" 
                + routeChangesHistory + '}';
    }

}
