//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.03 at 04:05:58 PM CET 
//


package bzh.terrevirtuelle.navisu.domain.rtz;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ScheduleElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScheduleElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="extensions" type="{http://www.cirm.org/RTZ/1/0}Extensions" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="waypointId" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="etd" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="etdWindowBefore" type="{http://www.w3.org/2001/XMLSchema}time" />
 *       &lt;attribute name="etdWindowAfter" type="{http://www.w3.org/2001/XMLSchema}time" />
 *       &lt;attribute name="eta" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="etaWindowBefore" type="{http://www.w3.org/2001/XMLSchema}time" />
 *       &lt;attribute name="etaWindowAfter" type="{http://www.w3.org/2001/XMLSchema}time" />
 *       &lt;attribute name="stay" type="{http://www.w3.org/2001/XMLSchema}time" />
 *       &lt;attribute name="speed" type="{http://www.cirm.org/RTZ/1/0}SpeedType" />
 *       &lt;attribute name="speedWindow" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="windSpeed" type="{http://www.cirm.org/RTZ/1/0}SpeedType" />
 *       &lt;attribute name="windDirection" type="{http://www.cirm.org/RTZ/1/0}CourseType" />
 *       &lt;attribute name="currentSpeed" type="{http://www.cirm.org/RTZ/1/0}SpeedType" />
 *       &lt;attribute name="currentDirection" type="{http://www.cirm.org/RTZ/1/0}CourseType" />
 *       &lt;attribute name="windLoss" type="{http://www.cirm.org/RTZ/1/0}SpeedType" />
 *       &lt;attribute name="waveLoss" type="{http://www.cirm.org/RTZ/1/0}SpeedType" />
 *       &lt;attribute name="totalLoss" type="{http://www.cirm.org/RTZ/1/0}SpeedType" />
 *       &lt;attribute name="rpm" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="pitch" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="fuel" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="relFuelSave" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="absFuelSace" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="Note" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScheduleElement", propOrder = {
    "extensions"
})
public class ScheduleElement {

    protected Extensions extensions;
    @XmlAttribute(name = "waypointId", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger waypointId;
    @XmlAttribute(name = "etd")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar etd;
    @XmlAttribute(name = "etdWindowBefore")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar etdWindowBefore;
    @XmlAttribute(name = "etdWindowAfter")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar etdWindowAfter;
    @XmlAttribute(name = "eta")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eta;
    @XmlAttribute(name = "etaWindowBefore")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar etaWindowBefore;
    @XmlAttribute(name = "etaWindowAfter")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar etaWindowAfter;
    @XmlAttribute(name = "stay")
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar stay;
    @XmlAttribute(name = "speed")
    protected BigDecimal speed;
    @XmlAttribute(name = "speedWindow")
    protected BigDecimal speedWindow;
    @XmlAttribute(name = "windSpeed")
    protected BigDecimal windSpeed;
    @XmlAttribute(name = "windDirection")
    protected BigDecimal windDirection;
    @XmlAttribute(name = "currentSpeed")
    protected BigDecimal currentSpeed;
    @XmlAttribute(name = "currentDirection")
    protected BigDecimal currentDirection;
    @XmlAttribute(name = "windLoss")
    protected BigDecimal windLoss;
    @XmlAttribute(name = "waveLoss")
    protected BigDecimal waveLoss;
    @XmlAttribute(name = "totalLoss")
    protected BigDecimal totalLoss;
    @XmlAttribute(name = "rpm")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger rpm;
    @XmlAttribute(name = "pitch")
    protected BigInteger pitch;
    @XmlAttribute(name = "fuel")
    protected BigDecimal fuel;
    @XmlAttribute(name = "relFuelSave")
    protected BigDecimal relFuelSave;
    @XmlAttribute(name = "absFuelSace")
    protected BigDecimal absFuelSace;
    @XmlAttribute(name = "Note")
    protected String note;

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link Extensions }
     *     
     */
    public Extensions getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Extensions }
     *     
     */
    public void setExtensions(Extensions value) {
        this.extensions = value;
    }

    /**
     * Gets the value of the waypointId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWaypointId() {
        return waypointId;
    }

    /**
     * Sets the value of the waypointId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWaypointId(BigInteger value) {
        this.waypointId = value;
    }

    /**
     * Gets the value of the etd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEtd() {
        return etd;
    }

    /**
     * Sets the value of the etd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEtd(XMLGregorianCalendar value) {
        this.etd = value;
    }

    /**
     * Gets the value of the etdWindowBefore property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEtdWindowBefore() {
        return etdWindowBefore;
    }

    /**
     * Sets the value of the etdWindowBefore property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEtdWindowBefore(XMLGregorianCalendar value) {
        this.etdWindowBefore = value;
    }

    /**
     * Gets the value of the etdWindowAfter property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEtdWindowAfter() {
        return etdWindowAfter;
    }

    /**
     * Sets the value of the etdWindowAfter property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEtdWindowAfter(XMLGregorianCalendar value) {
        this.etdWindowAfter = value;
    }

    /**
     * Gets the value of the eta property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEta() {
        return eta;
    }

    /**
     * Sets the value of the eta property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEta(XMLGregorianCalendar value) {
        this.eta = value;
    }

    /**
     * Gets the value of the etaWindowBefore property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEtaWindowBefore() {
        return etaWindowBefore;
    }

    /**
     * Sets the value of the etaWindowBefore property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEtaWindowBefore(XMLGregorianCalendar value) {
        this.etaWindowBefore = value;
    }

    /**
     * Gets the value of the etaWindowAfter property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEtaWindowAfter() {
        return etaWindowAfter;
    }

    /**
     * Sets the value of the etaWindowAfter property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEtaWindowAfter(XMLGregorianCalendar value) {
        this.etaWindowAfter = value;
    }

    /**
     * Gets the value of the stay property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStay() {
        return stay;
    }

    /**
     * Sets the value of the stay property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStay(XMLGregorianCalendar value) {
        this.stay = value;
    }

    /**
     * Gets the value of the speed property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSpeed(BigDecimal value) {
        this.speed = value;
    }

    /**
     * Gets the value of the speedWindow property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSpeedWindow() {
        return speedWindow;
    }

    /**
     * Sets the value of the speedWindow property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSpeedWindow(BigDecimal value) {
        this.speedWindow = value;
    }

    /**
     * Gets the value of the windSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWindSpeed() {
        return windSpeed;
    }

    /**
     * Sets the value of the windSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWindSpeed(BigDecimal value) {
        this.windSpeed = value;
    }

    /**
     * Gets the value of the windDirection property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWindDirection() {
        return windDirection;
    }

    /**
     * Sets the value of the windDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWindDirection(BigDecimal value) {
        this.windDirection = value;
    }

    /**
     * Gets the value of the currentSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCurrentSpeed() {
        return currentSpeed;
    }

    /**
     * Sets the value of the currentSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCurrentSpeed(BigDecimal value) {
        this.currentSpeed = value;
    }

    /**
     * Gets the value of the currentDirection property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCurrentDirection() {
        return currentDirection;
    }

    /**
     * Sets the value of the currentDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCurrentDirection(BigDecimal value) {
        this.currentDirection = value;
    }

    /**
     * Gets the value of the windLoss property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWindLoss() {
        return windLoss;
    }

    /**
     * Sets the value of the windLoss property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWindLoss(BigDecimal value) {
        this.windLoss = value;
    }

    /**
     * Gets the value of the waveLoss property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWaveLoss() {
        return waveLoss;
    }

    /**
     * Sets the value of the waveLoss property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWaveLoss(BigDecimal value) {
        this.waveLoss = value;
    }

    /**
     * Gets the value of the totalLoss property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalLoss() {
        return totalLoss;
    }

    /**
     * Sets the value of the totalLoss property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalLoss(BigDecimal value) {
        this.totalLoss = value;
    }

    /**
     * Gets the value of the rpm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRpm() {
        return rpm;
    }

    /**
     * Sets the value of the rpm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRpm(BigInteger value) {
        this.rpm = value;
    }

    /**
     * Gets the value of the pitch property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPitch() {
        return pitch;
    }

    /**
     * Sets the value of the pitch property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPitch(BigInteger value) {
        this.pitch = value;
    }

    /**
     * Gets the value of the fuel property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFuel() {
        return fuel;
    }

    /**
     * Sets the value of the fuel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFuel(BigDecimal value) {
        this.fuel = value;
    }

    /**
     * Gets the value of the relFuelSave property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRelFuelSave() {
        return relFuelSave;
    }

    /**
     * Sets the value of the relFuelSave property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRelFuelSave(BigDecimal value) {
        this.relFuelSave = value;
    }

    /**
     * Gets the value of the absFuelSace property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAbsFuelSace() {
        return absFuelSace;
    }

    /**
     * Sets the value of the absFuelSace property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAbsFuelSace(BigDecimal value) {
        this.absFuelSace = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    @Override
    public String toString() {
        return "ScheduleElement{" + "extensions=" + extensions + ", waypointId=" + waypointId + ", etd=" + etd + ", etdWindowBefore=" + etdWindowBefore + ", etdWindowAfter=" + etdWindowAfter + ", eta=" + eta + ", etaWindowBefore=" + etaWindowBefore + ", etaWindowAfter=" + etaWindowAfter + ", stay=" + stay + ", speed=" + speed + ", speedWindow=" + speedWindow + ", windSpeed=" + windSpeed + ", windDirection=" + windDirection + ", currentSpeed=" + currentSpeed + ", currentDirection=" + currentDirection + ", windLoss=" + windLoss + ", waveLoss=" + waveLoss + ", totalLoss=" + totalLoss + ", rpm=" + rpm + ", pitch=" + pitch + ", fuel=" + fuel + ", relFuelSave=" + relFuelSave + ", absFuelSace=" + absFuelSace + ", note=" + note + '}';
    }

}
