//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.03 at 04:05:58 PM CET 
//
package bzh.terrevirtuelle.navisu.domain.rtz;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Waypoint complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="Waypoint">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="position" type="{http://www.cirm.org/RTZ/1/0}GM_Point"/>
 *         &lt;element name="leg" type="{http://www.cirm.org/RTZ/1/0}Leg" minOccurs="0"/>
 *         &lt;element name="extensions" type="{http://www.cirm.org/RTZ/1/0}Extensions" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="revision" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="radius" type="{http://www.cirm.org/RTZ/1/0}RadiusType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Waypoint", propOrder = {
    "position",
    "leg",
    "extensions"
})
public class Waypoint {

    @XmlElement(required = true)
    protected GMPoint position;
    protected Leg leg;
    protected Extensions extensions;
    @XmlAttribute(name = "id", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger id;
    @XmlAttribute(name = "revision")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger revision;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "radius")
    protected BigDecimal radius;

    /**
     * Gets the value of the position property.
     *
     * @return possible object is {@link GMPoint }
     *
     */
    public GMPoint getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     *
     * @param value allowed object is {@link GMPoint }
     *
     */
    public void setPosition(GMPoint value) {
        this.position = value;
    }

    /**
     * Gets the value of the leg property.
     *
     * @return possible object is {@link Leg }
     *
     */
    public Leg getLeg() {
        return leg;
    }

    /**
     * Sets the value of the leg property.
     *
     * @param value allowed object is {@link Leg }
     *
     */
    public void setLeg(Leg value) {
        this.leg = value;
    }

    /**
     * Gets the value of the extensions property.
     *
     * @return possible object is {@link Extensions }
     *
     */
    public Extensions getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     *
     * @param value allowed object is {@link Extensions }
     *
     */
    public void setExtensions(Extensions value) {
        this.extensions = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the revision property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getRevision() {
        return revision;
    }

    /**
     * Sets the value of the revision property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setRevision(BigInteger value) {
        this.revision = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the radius property.
     *
     * @return possible object is {@link BigDecimal }
     *
     */
    public BigDecimal getRadius() {
        return radius;
    }

    /**
     * Sets the value of the radius property.
     *
     * @param value allowed object is {@link BigDecimal }
     *
     */
    public void setRadius(BigDecimal value) {
        this.radius = value;
    }

    @Override
    public String toString() {
        return "Waypoint{"
                + position != null ? "position=" + position : ""
                        + leg != null ? ", leg=" + leg : ""
                                + extensions != null ? ", extensions=" + extensions : ""
                                        + id != null ? ", id=" + id : ""
                                                + revision != null ? ", revision=" + revision : ""
                                                        + name != null ? ", name=" + name : ""
                                                                + radius != null ? ", radius=" + radius : ""
                                                                        + '}';
    }

}
